### ISSUE TITLE
Decide on a naming convention for packages

### ISSUE THREAD

**Issue by jhollway** [jhollway/qdatr#14]

**Comment by henriquesposito** [comment]
I would suggest that, if we go with multiple packages, they can all be called q-(short name for issue/type)-r. For example, the environment package could be called "qenvr". Another suggestion would be that they are called ggo-(short name for issue/type). For example, ggotrade or ggosec.

**Comment by jhollway** [comment]
An alternative could be issue-unit combinations, perhaps with a 'q' prefix, e.g. {*qEnvAgree*}.

**Comment by henriquesposito** [comment]
I think unit-issue combinations are a better way to proceed as a naming convention for packages.
