### ISSUE TITLE
JSON vs CSV for raw data

### ISSUE THREAD

**Issue by jhollway** [jhollway/qdatr#15]

**Comment by henriquesposito** [comment]
I think the "JSON question?" is already covered in this issue. But if you would like I can create a new separate issue. If we are using JSON for raw data, what does that entail for the package development? Do we depend on the jsonlite and tibble packages then to be able to work with the data?

**Comment by jhollway** [comment]
Copy comment from other issue:
One option could be to base off JSON and then convert to a tibble that is structured in a particular way: e.g. https://hendrikvanb.gitlab.io/2018/07/nested_data-json_to_tibble/

**Comment by henriquesposito** [comment]
There is also another package that was released a few months ago that transforms JSON data into tidy data frames in R (https://mran.microsoft.com/snapshot/2016-08-05/web/packages/tidyjson/vignettes/introduction-to-tidyjson.html). The package is called tidyjason and appears to be a simpler alternative to jsonlite to tibble conversion in one package (https://cran.r-project.org/web/packages/tidyjson/tidyjson.pdf).

**Comment by jhollway** [comment]
Decisions:

1. Using CSV, Excel or other for existing datasets that are incorporated.
1. Using JSON for holding web-scraped metadata or any other marked up data in progress.
