### ISSUE TITLE
Learn Zenhub best practices

### ISSUE THREAD

**Issue by jhollway** [jhollway/qdatr#17]

**Comment by henriquesposito** [comment]
Zenhub's help center has links that explain very well how to set up, work with and integrate Zenhub and GitHub to be more efficient (https://help.zenhub.com/support/home). There is also an Youtube channel with quick video tutorials that I found especially helpful (youtube.com/c/ZenHubIO/videos). The video on moving from GitHub to Zenhub is specially helpful for organization tips (https://www.youtube.com/watch?v=ppVA_hE3U3E), as well as the video on issues, milestones and epics (https://www.youtube.com/watch?v=tJ375ju3xTc) is helpful to show how these interact in terms of time. 

Should we organize our pipelines better in Zenhub? Following the tutorials perhaps we should create pipelines for issues in progress (to be completed within 2 weeks), issues in the backlog (to be completed soon but not a priority), milestone (all of issues that are to be completed within 1 to 3 weeks in a sprint) and epics (group of milestones and issues completed within 3 to 6 weeks). Doing this earlier on Zenhub might avoid us having to re-organize all issues and pipelines later on when they add up to be many more. This is also a more helpful way to plan according to time, priorities and goals of the project.

**Comment by jhollway** [comment]
Go for it. Please organise Zenhub as best you can, and then we'll confer this afternoon.
