### ISSUE TITLE
Decide on S3 or S4 class

### ISSUE THREAD

**Issue by jhollway** [jhollway/qdatr#2]

**Comment by jhollway** [comment]
Is it worth building off the back of Bioconductor and their annotation implementation?

**Comment by jhollway** [comment]
One option could be to base off JSON and then convert to a tibble that is structured in a particular way: e.g. https://hendrikvanb.gitlab.io/2018/07/nested_data-json_to_tibble/

**Comment by henriquesposito** [comment]
We have decided on S3.

**Comment by jhollway** [comment]
@henriquesposito can you create a new issue re: the JSON question? I'm closing this.
