### ISSUE TITLE
Decide on which functions are useful and we can take/modify from Gnevar 

### ISSUE THREAD

**Issue by henriquesposito** [jhollway/qDatr#22]

**Comment by henriquesposito** [comment]
Should we just take most of the functions and copy in qdatr?

**Comment by jhollway** [comment]
No, let's do it step by step as needed. This will keep things cleaner. Besides, a number of these functions may need to be altered to treat nested nibbles etc.

**Comment by jhollway** [comment]
Identify which functions from `{gnevar}` are required to be imported into `{qDatr}` so that the first datahouse/databox/datacube for `{qStates}` can be constructed.

Please write them up as new `{qDatr}` issues for tracking.
