### ISSUE TITLE
Add resequence () function to qDatr

### ISSUE THREAD

**Issue by henriquesposito** [jhollway/qDatr#23]
The function sorts and filters dates.

**Comment by henriquesposito** [comment]
I added this function and documentation to the develop branch. The example is still missing.

**Comment by henriquesposito** [comment]
I added a resequence function to qDatar. (I mistakenly committed to qStates beforehand, apologies for that.)

Just one question, should we have each function have its own R script file or should we aggregate these functions into a wrangling or standardizing R scripts as you do in gnevar?

**Comment by jhollway** [comment]
Collecting related functions together into a single script can help retain some order once the number of functions increases.

**Comment by henriquesposito** [comment]
The resequence() function requires that the interleave() function is also added to the qDatr package. Should we go ahead and add the interleave function? Otherwise PR checks will not pass.
