### ISSUE TITLE
Some dates seem to be in the incorrect century

### ISSUE THREAD

**Issue by jhollway** [jhollway/qdatr#5]
## Checklist before proceeding

- [ ] I have restarted R and the bug is still there
- [ ] I have restarted my OS and the bug is still there

## Brief description of the problem

Please briefly describe your problem and what output you expect. 

## Please include a minimal reproducible example (AKA a reprex). 

If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

```r
# insert reprex here
```

*If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.*

**Comment by henriquesposito** [comment]
I do not know if this is still an issue (?). I see you have several functions for the standardization of names and dates under the data_standardize.R file. If the issue of dates remain, we can try and attempt to locate inconsistencies manually in the data already in Gnevar and write more lines of code to standardize these dates.
